Portfolio/Controllers/HighScoreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Portfolio.Models;

namespace Portfolio.Controllers
{
    //https://dotnettutorials.net/lesson/viewdata-asp-net-core-mvc/

    public class HighScoreController : Controller
    {
        IList<HighScoreModel> highScoreList = new List<HighScoreModel>();

        //string connection =
        //    @"Data Source = 192.168.0.35;
        //    user Id = sa;
        //    password = Password321!;
        //    Initial Catalog = PortfolioGame;";
        string connection = @"Server = tcp:portfoliojeremiah.database.windows.net,1433;Initial Catalog = Portfolio_db; Persist Security Info=False;User ID = jeremiah; Password = Password321!; MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout = 30;";


        public ViewResult Index()
        {
            ViewData["Title"] = "High Score Page";
            ViewData["Header"] = "High Score Tile Puzzles";
            ViewDataStuffer();
            ViewData["HighScoreModel"] = highScoreList;
            return View();
        }

        public void ViewDataStuffer()
        {
            string connectionString = connection;

            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    SqlCommand cmd = new SqlCommand(
                        "Select PlayerScore, PlayerName From MyUser " +
                        "Where PlayerScore " +
                        "In (Select PlayerScore) " +
                        "Order By PlayerScore Desc;", connection);
                    connection.Open();
                    SqlDataReader sdr1 = cmd.ExecuteReader();

                    while (sdr1.Read())
                    {
                        highScoreList.Add(new HighScoreModel(sdr1["PlayerName"].ToString(), Int32.Parse(sdr1["PlayerScore"].ToString())));
                    }

                    connection.Close();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Something went wrong.\n" + ex);
            }
        }
    }
}

        //public IActionResult Index()
        //{
        //    return View();
        //}

        //public IActionResult Index()
        //{
        //    ViewDataStuffer();
        //    ViewDataStuffer2();
        //    return View();
        //}



        //public void ViewDataStuffer()
        //{
        //    try
        //    {
        //        IList<int> dataScores = new List<int>();
        //        IList<HighScoreModel> dataScores = new List<HighScoreModel>();
        //        string connectionString = connection;

        //        using (SqlConnection connection = new SqlConnection(connectionString))
        //        {
        //            SqlCommand cmd1 = new SqlCommand(
        //                "Select Top 5 PlayerScore From MyUser " +
        //                "Where PlayerScore " +
        //                "In (Select PlayerScore) " +
        //                "Order By PlayerScore Desc;", connection);
        //            connection.Open();
        //            SqlDataReader sdr1 = cmd1.ExecuteReader();

        //            while (sdr1.Read())
        //            {
        //                dataScores.Add(Int32.Parse(sdr1["PlayerScore"].ToString()));
        //                dataScores.Add(Int32.Parse(sdr1));
        //                dataScores.Add(new HighScoreModel() { PlayerScore.To = "sdr1" });
        //            }

        //            ViewData["Message0.0"] = dataScores[0];
        //            ViewData["Message1.0"] = dataScores[1];
        //            ViewData["Message2.0"] = dataScores[2];
        //            ViewData["Message3.0"] = dataScores[3];
        //            ViewData["Message4.0"] = dataScores[4];

        //            ViewData["myScores"] = dataScores.Count.ToString();

        //            connection.Close();
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        Console.WriteLine("Something went wrong.\n" + ex);
        //    }
        //}

        //public void ViewDataStuffer2()
        //{
        //    List<string> dataFirstNames = new List<string>();
        //    string connectionString = connection;

        //    try
        //    {
        //        using (SqlConnection connection = new SqlConnection(connectionString))
        //        {
        //            SqlCommand cmd2 = new SqlCommand(
        //                "Select Top 5 PlayerName From MyUser " +
        //                "Where PlayerScore " +
        //                "In (Select PlayerScore) " +
        //                "Order By PlayerScore Desc;", connection);
        //            connection.Open();
        //            SqlDataReader sdr2 = cmd2.ExecuteReader();

        //            while (sdr2.Read())
        //            {
        //                dataFirstNames.Add(sdr2["PlayerName"].ToString());
        //            }

        //            ViewData["Message0.1"] = dataFirstNames[0];
        //            ViewData["Message1.1"] = dataFirstNames[1];
        //            ViewData["Message2.1"] = dataFirstNames[2];
        //            ViewData["Message3.1"] = dataFirstNames[3];
        //            ViewData["Message4.1"] = dataFirstNames[4];
        //            connection.Close();
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        Console.WriteLine("Something went wrong.\n" + ex);
        //    }
        //}

        //public void CreateOutput()
        //{
        //    try
        //    {
        //        User user = new User();

        //        List<string> dataFirstNames = new List<string>();
        //        List<string> dataLastNames = new List<string>();
        //        List<int> dataScores = new List<int>();
        //        string connectionString = connection;

        //        using (SqlConnection connection = new SqlConnection(connectionString))
        //        {
        //            SqlCommand cmd = new SqlCommand(
        //                "Select Top 5 * From MyUser " +
        //                "Where PlayerScore " +
        //                "In (Select PlayerScore) " +
        //                "Order By PlayerScore Desc;", connection);
        //            connection.Open();
        //            SqlDataReader sdr = cmd.ExecuteReader();

        //            while (sdr.Read())
        //            {
        //                dataScores.Add(Int32.Parse(sdr["PlayerScore"].ToString()));
        //                dataFirstNames.Add(sdr["PlayerFirstName"].ToString());
        //                dataLastNames.Add(sdr["PlayerLastName"].ToString());
        //            }

        //            for (int i = 0; i < dataScores.Count; i++)
        //            {
        //                //scores[i].text = dataScores[i].ToString();
        //                user.PlayerScore = dataScores[i];
        //            }

        //            for (int i = 0; i < dataFirstNames.Count; i++)
        //            {
        //                //firstNames[i].text = dataFirstNames[i];
        //                user.PlayerNameFirst = dataFirstNames[i];
        //            }

        //            for (int i = 0; i < dataLastNames.Count; i++)
        //            {
        //                //lastNames[i].text = dataLastNames[i];
        //                user.PlayerNameLast = dataLastNames[i];
        //            }

        //            connection.Close();
        //        }
        //    }
        //    catch (System.Exception ex)
        //    {
        //        Console.WriteLine("Something went wrong.\n" + ex);
        //    }
        //}
    //}
//}

Portfolio/Controllers/JokesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Portfolio.Data;
using Portfolio.Models;

namespace Portfolio.Controllers
{
    public class JokesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JokesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Jokes
        public async Task<IActionResult> Index()
        {
              return View(await _context.Joke.ToListAsync());
        }

        // GET: Jokes/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        //// POST: Jokes/ShowSearchResults ?? Test View connected
        //public string ShowSearchResults(string SearchPhrase)
        //{
        //    return "You entered " + SearchPhrase;
        //}

        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            return View("Index", await _context.Joke.Where(j => j.JokeQuestion.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: Jokes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Joke == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        // GET: Jokes/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jokes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JokeQuestion,JokeAnswer")] Joke joke)
        {
            if (ModelState.IsValid)
            {
                _context.Add(joke);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(joke);
        }

        // GET: Jokes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Joke == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke.FindAsync(id);
            if (joke == null)
            {
                return NotFound();
            }
            return View(joke);
        }

        // POST: Jokes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JokeQuestion,JokeAnswer")] Joke joke)
        {
            if (id != joke.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(joke);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JokeExists(joke.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(joke);
        }

        // GET: Jokes/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Joke == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        // POST: Jokes/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Joke == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Joke'  is null.");
            }
            var joke = await _context.Joke.FindAsync(id);
            if (joke != null)
            {
                _context.Joke.Remove(joke);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JokeExists(int id)
        {
          return _context.Joke.Any(e => e.Id == id);
        }
    }
}

Portfolio/Controllers/VideoGamesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Portfolio.Controllers
{
    public class VideoGamesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Portfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Portfolio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Portfolio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HighScore" asp-action="Index">HighScores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VideoGames" asp-action="Index">Video Games</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="Index">Jokes</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Portfolio - Powered by: <strong>SmileyFaceStudios and Kelper</strong> - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <div class="social-media">
                <a href="https://www.facebook.com/jeremiah.miranda.98"><img src="~/Img/facebook2.png" /></a>
                <a href="https://www.instagram.com/bub2k44/"><img src="~/Img/instagram.png" /></a>
                <a href="https://www.youtube.com/channel/UC35i6pVKUtESHKkB346Mj7g"><img src="~/Img/youtube.png" /></a>
                <a href="https://www.linkedin.com/in/jeremiah-miranda-1b298147/"><img src="~/Img/linkedin.png" /></a>
            </div>

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>